name: Validate Branch Name

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name format
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "🔎 Checking branch name: $BRANCH_NAME"

          # Regex explanation:
          # ^(fix|release|feat|hotfix|build|test) → allowed types
          # /[a-z0-9._-]+ → branch name (lowercase, numbers, dash, underscore, dot)
          # /[A-Z]+-[0-9]+ → JIRA Project + Ticket number (e.g., FECA-123)
          #
          if [[ ! "$BRANCH_NAME" =~ ^(fix|release|feat|hotfix|build|test)/[a-z0-9._-]+/[A-Z]+-[0-9]+$ ]]; then
            echo "❌ Invalid branch name!"
            echo "👉 Expected format: type/branch-name/JIRA-PROJECT-TICKET"
            echo "✅ Examples:"
            echo "   feat/auth/FECA-27"
            echo "   fix/cart/FECA-101"
            exit 1
          fi

          echo "✅ Branch name is valid!"
